[package]
name = "near-network"
version = "0.0.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.62.1"
publish = false

[build-dependencies]
anyhow = "1.0.55"
protobuf-codegen = "3.0.1"

[dependencies]
actix = "0.13.0"
anyhow = "1.0.55"
arc-swap = "1.5"
assert_matches = "1.3"
borsh = { version = "0.9", features = ["rc"] }
bytes = "1"
bytesize = "1.1"
chrono = "0.4.4"
conqueue = "0.4.0"
crossbeam-channel = "0.5"
deepsize = { version = "0.2.0", optional = true }
futures = "0.3"
futures-util = "0.3"
im = "15"
itertools = "0.10.3"
lru = "0.7.2"
near-rust-allocator-proxy = { version = "0.4", optional = true }
once_cell = "1.12.0"
opentelemetry = { version = "0.17", features = ["trace"] }
parking_lot = "0.12.1"
pin-project-lite = "0.2.9"
protobuf = "3.0.1"
rand = "0.6"
rand_pcg = "0.1"
rayon = "1.5"
serde = { version = "1", features = ["alloc", "derive", "rc"] }
smart-default = "0.6"
strum = { version = "0.24", features = ["derive"] }
thiserror = "1"
tokio = { version = "1.1", features = ["net", "rt-multi-thread"] }
tokio-stream = { version = "0.1.2", features = ["net"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
tracing = "0.1.13"
tracing-opentelemetry = { version = "0.17" }

delay-detector = { path = "../../tools/delay_detector" }
near-o11y = { path = "../../core/o11y" }
near-crypto = { path = "../../core/crypto" }
near-metrics = { path = "../../core/metrics" }
near-network-primitives = { path = "../network-primitives" }
near-performance-metrics = { path = "../../utils/near-performance-metrics" }
near-performance-metrics-macros = { path = "../../utils/near-performance-metrics-macros" }
near-primitives = { path = "../../core/primitives" }
near-rate-limiter = { path = "../../utils/near-rate-limiter" }
near-stable-hasher = { path = "../../utils/near-stable-hasher"}
near-store = { path = "../../core/store" }
near-logger-utils = { path = "../../test-utils/logger" }

[dev-dependencies]
criterion = { version = "0.3.5", default_features = false, features = ["html_reports", "cargo_bench_support"] }
tempfile = "3"
pretty_assertions = "1.2"

[features]
deepsize_feature = [
    "deepsize",
    "near-crypto/deepsize_feature",
    "near-network-primitives/deepsize_feature",
    "near-primitives/deepsize_feature",
]
delay_detector = ["delay-detector/delay_detector"]
performance_stats = [
    "near-performance-metrics/performance_stats",
    "near-rust-allocator-proxy",
]
test_features = [
  "near-network-primitives/test_features",
]

[[bench]]
name = "graph"
harness = false

[[bench]]
name = "routing_table_actor"
harness = false
