[package]
name = "near-jsonrpc-primitives"
version = "0.0.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
publish = true
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.61.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/near/nearcore"
description = "This crate hosts structures for the NEAR JSON RPC Requests, Responses and Error types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "~0.8", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4.4", features = ["serde"] }
thiserror = "1.0"
serde_json = "1"
num-rational = { version = "0.3", features = ["serde"] }

near-crypto = { path = "../../core/crypto" }
near-account-id = { path = "../../core/account-id" }
near-primitives = { path = "../../core/primitives" }
near-rpc-error-macro = { path = "../../tools/rpctypegen/macro" }
near-client-primitives = { path = "../client-primitives" }

[features]
test_features = []
